const std = @import("std");

/// The type of artifact
pub const Type = enum {
    object,
    library,
    executable,
};

/// List of artifacts
pub const Collection = struct {
    list: std.ArrayListUnmanaged(Self) = .empty,

    pub fn deinit(self: *Collection, allocator: std.mem.Allocator) void {
        for (self.list.items) |*artifact| {
            artifact.deinit(allocator);
        }

        self.list.deinit(allocator);
    }

    pub fn add(self: *Collection, allocator: std.mem.Allocator, artifact: Self) !void {
        try self.list.append(allocator, artifact);
    }

    pub fn getByOutput(self: Collection, output: []const u8) ?Self {
        for (self.list.items) |artifact| {
            for (artifact.outputs.items) |item| {
                if (std.mem.eql(u8, item, output)) {
                    return artifact;
                }
            }
        }

        return null;
    }
};

/// Represents a single output generated by a list of inputs.
const Self = @This();

output_type: Type = .object,
inputs: std.ArrayListUnmanaged([]const u8) = .empty,
outputs: std.ArrayListUnmanaged([]const u8) = .empty,
flags: std.StringHashMapUnmanaged(void) = .empty,

pub fn deinit(self: *Self, allocator: std.mem.Allocator) void {
    self.inputs.deinit(allocator);
    self.outputs.deinit(allocator);
    self.flags.deinit(allocator);
}

pub fn getOutputName(self: Self) ?[]const u8 {
    if (self.outputs.items.len == 0) return null;
    return self.outputs.items[0];
}
